### ISSUE TITLE
any way for Custom Error Messsage

### ISSUE THREAD

**Issue by RiteshM** [oauthjs/node-oauth2-server#12]
i have  two doubt 
1. i got the point of implementing all the functions but where function getAccessToken and getRefreshToken utilized or called ?? i get the point from your comment How to implement.
2.when ever i pass an error in any function like

model.saveAccessToken = function (accessToken, clientId, userId, expires, callback) {

callback({'error':'invalid response'},false);

};

then it will give the response 
{
code: 503
error: "server_error"
error_description: "server_error"
} 
if there is any custom mistake or error then can i change this response to some thing else manually .can i customize error message using this library??

**Comment by kreck** [comment]
old issue but i have a case - maybe you can provide a quick workaround.

I use JWT which required me to rewrite the model.getAccessToken implementation. I use a try/catch block to decode the JTW. If it fails this is usually due to a decoding error, and hence a "invalid_token" error. However it produces a "server_error" - any suggestions?

**Comment by prameshbajra** [comment]
Any updates on this? Being able to create custom messages would be more easier for a lazy ass like me. :smile:
