### ISSUE TITLE
Is there any option to ignore the clientId and clientSecret?

### ISSUE THREAD

**Issue by DvirH** [oauthjs/node-oauth2-server#310]
In most of the oauth2 the client-id and secret-id are not mandatory fields, so the user can post for token with username, password and grant_type only.
How can I change the library to work like that?

**Comment by maxtruxa** [comment]
Per the OAuth 2.0 specification 4.3.2:

> If the client type is confidential or **the client was issued client
> credentials** (or assigned other authentication requirements), the
> client MUST authenticate with the authorization server as described
> in Section 3.2.1.

And a bit further down:

> The authorization server MUST:
>
>    o  require client authentication for confidential clients or **for any
>       client that was issued client credentials** (or with other
>       authentication requirements),

*Note: Emphasis added by me.*

Since you shouldn't issue tokens for unregistered clients (for the reasons listed in section 3.2.1), it could be argued that requiring the `client_id` and `client_secret` is usually correct. Without the binding of the issued token to a specific client, you would lose the ability to...
- ... revoke all tokens issued to the client
- ... check if the client is allowed to use the `password` grant at all
- ... check if the client is allowed to issue tokens for the requested scopes (if any)
- ... and probably a lot more.

This way OAuth would be just another login mechanism (username + password = token), comparable to the login session used by websites. If this is what you want OAuth is probably not the right tool.

If you need this behavior anyway, you would have to add a flag to skip all checks for `client` in the path used by the `password` grant. That's quite a lot of modifications.

**Comment by maxtruxa** [comment]
Since #346 got merged in you can now allow access requests without a `client_secret` for selected grants by using the `requiresClientAuthentication` server option. `client_id` is still required (and we'll probably keep it that way since OAuth wouldn't make much sense without it, for the reasons listed above).
