### ISSUE TITLE
validateScope signature

### ISSUE THREAD

**Issue by chainlink** [oauthjs/node-oauth2-server#335]
In the docs `validateScope` has a signature `validateScope(token, scope)` but I notice in the code it takes `validateScope(user, client, scope)` as parameters, which one should I implement? (and how does scope validation work with (user, client, scope)

https://github.com/oauthjs/node-oauth2-server/blob/e1dfa3d1fb555660e7ef4f478b2a9ada925572dc/lib/grant-types/abstract-grant-type.js#L99

Thanks! Looking forward to the release, we're doing a big push to bring our implementation up to the 3.0 spec.

**Comment by maxtruxa** [comment]
With v3 there are two separate scope related model functions: `validateScope` and `verifyScope`.

---

## validateScope

`validateScope` is invoked during the authorization code, password and client credentials grant to check if the requested `scope` is valid for a particular `client`/`user` combination.

This model function is **optional**. If not implemented, any scope is accepted.

```
validateScope(user, client, scope)
```

**user**: *Object*

The user object previously obtained through `model#getUserFromClient` (client credentials grant), `model#getUser` (password grant) or `model#getAuthorizationCode` (`code.user`; authorization code grant).

**client**: *Object*

The client object previously obtained through `model#getClient` (all grants).

**scope**: *String*

The requested scopes extracted from the request.

**returns**: *String*/*falsy*

Validated scopes to be used or a falsy value to reject the requested scopes.
In theorie you can return any type (e.g. an array), as the result is passed to `model#saveToken` without modification.

### Remarks

You can decide yourself whether you want to reject or accept partially valid scopes by simply filtering out invalid scopes and returning only valid ones.

---

## verifyScope

`verifyScope` is invoked during request authentication to check if the provided access token was authorized the required scopes.

This model function is **required**.

```
verifyScope(accessToken, scope)
```

**accessToken**: *Object*

The access token obtained through `model#getAccessToken`.

**scope**: *Any*

The required scope as given to `OAuth2Server#authenticate` as `options.scope`.

**returns**: *Boolean*

`true` if the access token passes the check, `false` otherwise.

---

> This is an excerpt from the DOCS.md I'm currenty preparing.

**Comment by chainlink** [comment]
Amazing thanks! was prepping my own notes for a Docs update, but will wait on your DOCS.md 👍

**Comment by chainlink** [comment]
Can I assume this line is staying? https://github.com/oauthjs/node-oauth2-server/blob/237646e9848c3cdccf5d642bd2dfab78f2ed20ee/lib/handlers/authenticate-handler.js#L42

Looks like verifyScope is optional (only if scope passed into the server model) (Also scope is not mentioned in the current server options docs)

**Comment by maxtruxa** [comment]
Oh you're absolutely right, I missed that. Fixed in the previous comment. Thanks.
