### ISSUE TITLE
revokeToken should revoke access tokens or refresh tokens?

### ISSUE THREAD

**Issue by chainlink** [oauthjs/node-oauth2-server#337]
Save token saves an access token and optionally a refresh token.

Remove token ONLY removes an refresh token, correct?

**Comment by chainlink** [comment]
Also confirming revokeAccessToken has been removed?

**Comment by maxtruxa** [comment]
> Save token saves an access token and optionally a refresh token.

Correct.

> Remove token ONLY removes an refresh token, correct?

Correct. I stumbled across this too, but thinking about it, it makes sense.

`saveToken` receives a `token` object with an access token and optionally a refresh token set.
`revokeToken` receives a `token` object that *currently* only ever has a refresh token set.

> Also confirming revokeAccessToken has been removed?

I don't know about v2 (since you're asking there probably was one) but in v3 there is no model function `revokeAccessToken`. Access tokens are expected to expire, and explicit revocation has to be implemented separately.

**Comment by chainlink** [comment]
ok thanks!
