### ISSUE TITLE
Publish v3

### ISSUE THREAD

**Issue by mirceaalexandru** [oauthjs/node-oauth2-server#382]
Hey,

I need to implement oauth2 support for restify. I would like to know when v3 is scheduled to be published on npm, as I don't think using it from git is a good choice. The last version on npm is 2.4.1 which doesn't seem to have support for other frameworks than express.

BTW, great job for this module.

Thank you

**Comment by njj** [comment]
Have you tried installing @next? i.e. `npm install node-oauth2-server@next`

**Comment by mirceaalexandru** [comment]
Yes, I saw it but I assume that it is is a pre-release, an unstable version. Because I need it for a project that will be in production soon I don't think is OK to do that.

I will close this issue.
Thank you,
Mircea

**Comment by yusufsyaifudin** [comment]
Why are you close this issue? I think you (and so am I), want to get release schedule for version 3. I believe it is a critical concern in production since we must ensure all package we use in production has a stable version, so we have no doubt to ship it to users. 

Furthermore, I am concern that in version 3b will have a break changes when it released. Can someone confirm about it?

**Comment by manjeshpv** [comment]
@mirceaalexandru You can use npm install (node-oauth2-server@2.4.1)[https://www.npmjs.com/package/oauth2-server]

**Comment by mirceaalexandru** [comment]
@manjeshpv 2.4.1 do not have support for other frameworks - restify in my case - so it is not helping me, but thank you for your comment. This is why I asked about v3. 

@yusufsyaifudin I closed the issue because I end up implementing myself this library for my project, as I cannot wait too much for v3.
