### ISSUE TITLE
Docs point to fork, not main project

### ISSUE THREAD

**Issue by mjsalinger** [oauthjs/node-oauth2-server#416]
@maxtruxa The ReadTheDocs site points to your fork of the docs, not the main site.  This is the only impediment to pushing out v3.  Can you repoint?

**Comment by maxtruxa** [comment]
@mjsalinger Fixed.

I can't configure the webhook though because I don't have write access to this repo. If you create an account on [RTD](readthedocs.org) I can add you as a maintainer there (which gives admin access). How webhook integration with RTD is set up is documented [here](http://docs.readthedocs.io/en/latest/webhooks.html#github).

**Comment by mjsalinger** [comment]
@maxtruxa mjsalinger is my RTD username.  Also, did you create a slack team for this project?  If so, can you open it up, it doesn't let people register...

**Comment by mjsalinger** [comment]
Gave you permissions to set up the webhook as well..

**Comment by maxtruxa** [comment]
I configured the webhook and added you as a maintainer on RTD.

The Slack team was created by @manjeshpv, but I got owner access. Slack (sadly) is an invite-only platform.. I'll try to set up [slackin](https://github.com/rauchg/slackin) to automate invites asap.
