### ISSUE TITLE
Why even store the token if it is self-contained (JWT)?

### ISSUE THREAD

**Issue by wkamir** [oauthjs/node-oauth2-server#458]
This is really a great module, especially for learning what is going on with different flows. Thank you so much to everyone involved!

I have built a very simple example where in `model.generateAccessToken` I create a JWT (signed with a private key). This JWT is then used in subsequent requests to authenticate the request (it contains a scope for accessing the api)

The `authenticate()` middleware calls `model.getAccessToken` where I verify the JWT (with the public key).

I am just wondering: Where in all this would I even need to store and retrieve the token (since it is self-contained and sent around anyway).

Is this scenario unsafer than using a "reference-token" with which to acess the JWT from a database?

My `model.saveToken` literally looks like this now (nothing is stored):

```
module.exports.saveToken = (token, client, user, callback) => {
  let result = { client: {}, user: {} }

  extend(result, token);
  extend(result.client, client);
  extend(result.user, user);

  callback(null, result);
};
```

Everything seems to work just fine... What am I missing?

Thanks you for any enlightenment. I almost have a slight understanding of what oauth 2 is supposed to do...

**Comment by maxtruxa** [comment]
Using JWTs this way is perfectly fine unless you need the ability to revoke tokens before they expire.
Since you can't magically tell the JWT to "be revoked" (Hey, you can't even know that it exists if you haven't saved it anywhere ;)) you'd have to store every authorized token to prevent revoked tokens from being used. At which point we're back where we started: saving all issued tokens to a database.

**Comment by wkamir** [comment]
Thank you for clarifying this - I thought so. It's just that with everything concerning security I am extra carful to "get it right"..
