### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HenrikGr** [oauthjs/node-oauth2-server#469]
I'm trying to implement a model and using mongoose and mongodb and need clarification.
In the documentation it states this about the client object.
client (Object), containing at least an id property that matches the supplied client

What does this really mean, is it the clientId that is generated together with the client secret when I register a new client in my mongodb or is it the mongodb _id field value?

I have some success but I can not get the refresh_token request to work since it complains about token.client.id !== client.id.

The last question: Do you have any reference implementation - using mongoose/mongo?

**Comment by mjsalinger** [comment]
The `client.id` property is the OAuth clientId that is used in all OAuth requests.  Since we are database-agnostic, that can be any field in your data store (i.e. you could use `_id` in mongo to represent the client Id, or you could use some other property in your mongo collection, such as `clientId`.  What matters is that when you present the client entity to the library, that there is a property `client.id` that contains the `id` to match up against the OAuth request.

Unfortunately we don't currently have a mongoos reference implementation.

**Comment by HenrikGr** [comment]
Thanks. 
Like this project.
