### ISSUE TITLE
UserId is lost on a 2nd refresh token

### ISSUE THREAD

**Issue by BeeNoox** [oauthjs/node-oauth2-server#61]
Hi Thom,

I'm having an issue with refresh_token. Here is how I get it :
- A user is logged in, he receives an access token and a refresh token
- User sends authentified requests using access token, until...
- The access token has expired, the refresh token is used to give another access token and refresh token to the user.
- User sends authentified requests using access token, until...
- The access token has expired, the refresh token is used to give another access token and refresh token to the user, but **this time there is no UserId given to `saveAccessToken` and `saveRefreshToken`**, I save tokens in mongodb anyway.
- User sends authentified requests using access token, until...
- In `getRefreshToken`, error `No user/userId parameter returned from getRefreshToken` occurs, and the user is disconnected

Is it a normal behavior? Am I missing something?

Bye,
Alex

**Comment by artkoenig** [comment]
I have the same issue. With your examples provided I only get the right access token on the first call, after refreshing it, bad things happen (for testing purposes I use the in-memory model):

The user object is saved as `userId` in the access token object. In the `checkToken` method (`authorize.js`) the user is attached to the request:

```self.req.user = token.user ? token.user : { id: token.userId };```

after the first call I get:

```self.req.user = {id: user}``` (where user = my user model)

after the next auth token refresh, the new token is saved in `grant.js`:

```this.model.saveAccessToken(accessToken, this.client.clientId, expires, this.user, function (err)````

this transforms my model to `{userId: {id: user}}`, so in the next `checkToken` call my `req.user` is `{id: {id: user}}` and so on...

This line `self.req.user = token.user ? token.user : { id: token.userId };` did give me a hint to save my complete user object as `user` in the token, this solved my issue. Due to the fact, that this is not mentioned in you examples, I am not sure if this is the right behaviour
